In [ ]:
#1 sum of list
numbers=[23,24,25,26]
print("SUM OF ALL THE NUMBERS:",sum(numbers))


SUM OF ALL THE NUMBERS: 98


In [2]:
#1  sum for two list
numbers=[23,24,25,26]
num=[1,2,3,4]
addition=numbers+num
print(addition)
print(sum(numbers+num))
print(sum(addition))

[23, 24, 25, 26, 1, 2, 3, 4]
108
108


In [6]:
import numpy as np 
numbers=[23,24,25,26]
num=[1,2,3,4]
np.add(numbers,num)

array([24, 26, 28, 30])

In [7]:
#2 multiply
import numpy as np
numbers=[23,24,25,26]
num=[1,2,3,4]
np.multiply(numbers,num)

array([ 23,  48,  75, 104])

In [8]:
#3
numbers=[23,24,25,26]
print("GREATEST NUMBER:",max(numbers))
print("SMALLEST NUMBER:",min(numbers))

GREATEST NUMBER: 26
SMALLEST NUMBER: 23


In [9]:
#4
letters=['a','b','c','d','e']
print(letters.sort(reverse=True))
print(letters)

None
['e', 'd', 'c', 'b', 'a']


In [10]:
#5
alpha=[6,7,8,6,6,6]
updated_list=list(set(alpha))
print(updated_list)

[8, 6, 7]


In [11]:
#6
company=["apple","lenovo","google","samsung"]
company1=company.copy()
print(company1)

['apple', 'lenovo', 'google', 'samsung']


In [12]:
#7 count
alphabet=['a','b','c','a','a','a']
print(alphabet.count('a'))

4


In [13]:
# 8 sort in ascen
company=["apple","lenovo","google","samsung"]
company.sort()
print(company)

['apple', 'google', 'lenovo', 'samsung']


In [14]:
# 9 combine
x=["hello"]
y=["world"]
print(x+y)

['hello', 'world']


In [22]:
x=(["hello"])
y=(["world"])
print(x+y)

['hello', 'world']


In [21]:
#11
square=np.array([1,2,3,4])
square**2

array([ 1,  4,  9, 16])

In [ ]:
# 12 nested list
x=np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
#13
empty=np.empty([])
print(empty)

5e-324


In [ ]:
#14
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
common_items = list(set(list1) & set(list2))
print(common_items)

[4, 5]


In [17]:
#15 replace the last element
last_element=[23,24,25,26,27]
last_element[4]=30
print(last_element)


[23, 24, 25, 26, 30]
