In [1]:
import pandas as pd 
import numpy as np 
hotel_booking=pd.read_csv("hotel_bookings_updated_2024.csv")
hotel_booking

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel - Chandigarh            0        342               2024   
1           Resort Hotel - Mumbai            0        737               2024   
2            Resort Hotel - Delhi            0          7               2024   
3          Resort Hotel - Kolkata            0         13               2024   
4          Resort Hotel - Lucknow            0         14               2024   
...                           ...          ...        ...                ...   
119385          City Hotel - Pune            0         23               2024   
119386        City Hotel - Mumbai            0        102               2024   
119387       City Hotel - Lucknow            0         34               2024   
119388     City Hotel - Ahmedabad            0        109               2024   
119389        City Hotel - Bhopal            0        205               2024   

       arrival_date_month  arrival_date_week_number  \
0                    July                        30   
1                   April                        17   
2               September                        37   
3                  August                        33   
4               September                        37   
...                   ...                       ...   
119385          September                        39   
119386           November                        46   
119387              April                        16   
119388            October                        40   
119389           December                        51   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                              27                        0   
1                              28                        0   
2                              10                        0   
3                              14                        0   
4                              14                        0   
...                           ...                      ...   
119385                         29                        2   
119386                         16                        2   
119387                         19                        2   
119388                          5                        2   
119389                         21                        2   

        stays_in_week_nights  adults  ...  agent  company  \
0                          0       2  ...    NaN      NaN   
1                          0       2  ...    NaN      NaN   
2                          1       1  ...    NaN      NaN   
3                          1       1  ...  304.0      NaN   
4                          2       2  ...  240.0      NaN   
...                      ...     ...  ...    ...      ...   
119385                     5       2  ...  394.0      NaN   
119386                     5       3  ...    9.0      NaN   
119387                     5       2  ...    9.0      NaN   
119388                     5       2  ...   89.0      NaN   
119389                     7       2  ...    9.0      NaN   

       days_in_waiting_list customer_type     adr required_car_parking_spaces  \
0                         0     Transient    0.00                           0   
1                         0     Transient    0.00                           0   
2                         0     Transient   75.00                           0   
3                         0     Transient   75.00                           0   
4                         0     Transient   98.00                           0   
...                     ...           ...     ...                         ...   
119385                    0     Transient   96.14                           0   
119386                    0     Transient  225.43                           0   
119387                    0     Transient  157.71                           0   
119388                    0     Transient  104.40                           0   
119389                    0     Trans

In [2]:
hotel_booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [3]:
hotel_booking.describe()

is_canceled      lead_time  arrival_date_year  \
count  119390.000000  119390.000000           119390.0   
mean        0.370416     104.011416             2024.0   
std         0.482918     106.863097                0.0   
min         0.000000       0.000000             2024.0   
25%         0.000000      18.000000             2024.0   
50%         0.000000      69.000000             2024.0   
75%         1.000000     160.000000             2024.0   
max         1.000000     737.000000             2024.0   

       arrival_date_week_number  arrival_date_day_of_month  \
count             119390.000000              119390.000000   
mean                  26.375835                  15.723394   
std                   15.021596                   8.805079   
min                    1.000000                   1.000000   
25%                   13.000000                   8.000000   
50%                   26.000000                  16.000000   
75%                   39.000000                  23.000000   
max                   52.000000                  31.000000   

       stays_in_weekend_nights  stays_in_week_nights         adults  \
count            119390.000000         119390.000000  119390.000000   
mean                  0.927599              2.500302       1.856403   
std                   0.998613              1.908286       0.579261   
min                   0.000000              0.000000       0.000000   
25%                   0.000000              1.000000       2.000000   
50%                   1.000000              2.000000       2.000000   
75%                   2.000000              3.000000       2.000000   
max                  19.000000             50.000000      55.000000   

            children         babies  is_repeated_guest  \
count  119386.000000  119390.000000      119390.000000   
mean        0.103890       0.007949           0.031912   
std         0.398561       0.097436           0.175767   
min         0.000000       0.000000           0.000000   
25%         0.000000       0.000000           0.000000   
50%         0.000000       0.000000           0.000000   
75%         0.000000       0.000000           0.000000   
max        10.000000      10.000000           1.000000   

       previous_cancellations  previous_bookings_not_canceled  \
count           119390.000000                   119390.000000   
mean                 0.087118                        0.137097   
std                  0.844336                        1.497437   
min                  0.000000                        0.000000   
25%                  0.000000                        0.000000   
50%                  0.000000                        0.000000   
75%                  0.000000                        0.000000   
max                 26.000000                       72.000000   

       booking_changes          agent      company  days_in_waiting_list  \
count    119390.000000  103050.000000  6797.000000         119390.000000   
mean          0.221124      86.693382   189.266735              2.321149   
std           0.652306     110.774548   131.655015             17.594721   
min           0.000000       1.000000     6.000000              0.000000   
25%           0.000000       9.000000    62.000000              0.000000   
50%           0.000000      14.000000   179.000000              0.000000   
75%           0.000000     229.000000   270.000000              0.000000   
max          21.000000     535.000000   543.000000            391.000000   

                 adr  required_car_parking_spaces  total_of_special_requests  
count  119390.000000                119390.000000              119390.000000  
mean      101.831122                     0.062518                   0.571363  
std        50.535790                     0.245291                   0.792798  
min        -6.380000                     0.000000                   0.000000  
25%        69.290000                     0.000000                   0.000000  
50%        94.57500

In [4]:
hotel_booking.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [54]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
hotel_booking['country']=le.fit_transform(hotel_booking['country'])
hotel_booking['hotel']=le.fit_transform(hotel_booking['hotel'])
hotel_booking['arrival_date_month']=le.fit_transform(hotel_booking['arrival_date_month'])
hotel_booking['meal']=le.fit_transform(hotel_booking['meal'])
hotel_booking['market_segment']=le.fit_transform(hotel_booking['market_segment'])
hotel_booking['distribution_channel']=le.fit_transform(hotel_booking['distribution_channel'])
hotel_booking['reserved_room_type']=le.fit_transform(hotel_booking['reserved_room_type'])
hotel_booking['assigned_room_type']=le.fit_transform(hotel_booking['assigned_room_type'])
hotel_booking['deposit_type']=le.fit_transform(hotel_booking['deposit_type'])
hotel_booking['reservation_status']=le.fit_transform(hotel_booking['reservation_status'])
hotel_booking['reservation_status_date']=le.fit_transform(hotel_booking['reservation_status_date'])
hotel_booking['city']=le.fit_transform(hotel_booking['city'])
hotel_booking['city']=le.fit_transform(hotel_booking['city'])
hotel_booking['customer_type']=le.fit_transform(hotel_booking['customer_type'])


In [55]:
hotel_booking['country']=hotel_booking['country'].fillna(hotel_booking['country'].median())
hotel_booking['children']=hotel_booking['children'].fillna(hotel_booking['children'].median())

In [56]:

h_b=hotel_booking.drop(['company','agent'],axis=1)

In [57]:
h_b.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests   

In [58]:
hotel_booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 34 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  int64  
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  int64  
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [59]:
h_b['is_canceled'].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [60]:
from imblearn.under_sampling import RandomUnderSampler
x=h_b.drop(['is_canceled'],axis=1)
y=h_b['is_canceled']
smot=RandomUnderSampler(sampling_strategy='majority')
input,output=smot.fit_resample(x,y)

In [61]:
print(input.shape)
print(output.shape)

(88448, 31)
(88448,)


In [62]:
output.value_counts()

is_canceled
0    44224
1    44224
Name: count, dtype: int64

In [63]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x=scaler.fit_transform(x)

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(95512, 31)
(23878, 31)
(95512,)
(23878,)


In [65]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9899907864980316
[[14902     5]
 [  234  8737]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     14907
           1       1.00      0.97      0.99      8971

    accuracy                           0.99     23878
   macro avg       0.99      0.99      0.99     23878
weighted avg       0.99      0.99      0.99     23878



In [67]:
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
# this is  generalised as f1 score is same

0.9900326660524332
[[14903     4]
 [  234  8737]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     14907
           1       1.00      0.97      0.99      8971

    accuracy                           0.99     23878
   macro avg       0.99      0.99      0.99     23878
weighted avg       0.99      0.99      0.99     23878



In [69]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [70]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[14907     0]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14907
           1       1.00      1.00      1.00      8971

    accuracy                           1.00     23878
   macro avg       1.00      1.00      1.00     23878
weighted avg       1.00      1.00      1.00     23878



In [71]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_test,y_test)
y_pred=dt.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
# this also have generalised F1 score

1.0
[[14907     0]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14907
           1       1.00      1.00      1.00      8971

    accuracy                           1.00     23878
   macro avg       1.00      1.00      1.00     23878
weighted avg       1.00      1.00      1.00     23878



In [73]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)

In [74]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[14907     0]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14907
           1       1.00      1.00      1.00      8971

    accuracy                           1.00     23878
   macro avg       1.00      1.00      1.00     23878
weighted avg       1.00      1.00      1.00     23878



In [75]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_test,y_test)
y_pred=rfc.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
#

1.0
[[14907     0]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14907
           1       1.00      1.00      1.00      8971

    accuracy                           1.00     23878
   macro avg       1.00      1.00      1.00     23878
weighted avg       1.00      1.00      1.00     23878



In [77]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [78]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9946812965910042
[[14907     0]
 [  127  8844]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     14907
           1       1.00      0.99      0.99      8971

    accuracy                           0.99     23878
   macro avg       1.00      0.99      0.99     23878
weighted avg       0.99      0.99      0.99     23878



In [79]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_test,y_test)
y_pred=knn.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
# there is over fitting for knn

0.9922941619901164
[[14902     5]
 [  179  8792]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     14907
           1       1.00      0.98      0.99      8971

    accuracy                           0.99     23878
   macro avg       0.99      0.99      0.99     23878
weighted avg       0.99      0.99      0.99     23878



In [81]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)

In [82]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[14907     0]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14907
           1       1.00      1.00      1.00      8971

    accuracy                           1.00     23878
   macro avg       1.00      1.00      1.00     23878
weighted avg       1.00      1.00      1.00     23878



In [83]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(x_test,y_test)
y_pred=svc.predict(x_test)

In [84]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[14907     0]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14907
           1       1.00      1.00      1.00      8971

    accuracy                           1.00     23878
   macro avg       1.00      1.00      1.00     23878
weighted avg       1.00      1.00      1.00     23878



In [85]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)
y_pred=gb.predict(x_test)

In [86]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9945137783733982
[[14776   131]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     14907
           1       0.99      1.00      0.99      8971

    accuracy                           0.99     23878
   macro avg       0.99      1.00      0.99     23878
weighted avg       0.99      0.99      0.99     23878



In [87]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_test,y_test)
y_pred=gb.predict(x_test)

In [88]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9942625010469889
[[14770   137]
 [    0  8971]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     14907
           1       0.98      1.00      0.99      8971

    accuracy                           0.99     23878
   macro avg       0.99      1.00      0.99     23878
weighted avg       0.99      0.99      0.99     23878



In [ ]:
# therefore in this classification dataset KNN  alone has over fitting.